stages:
  - build
  - test
  - quality
  - deploy

variables:
  SOURCES_PATH: "src/main/java"
  TESTS_PATH: "src/test/java"
  BINARIES_PATH: "build/classes"
  JACOCO_EXEC_FILE : "build/jacoco/test.exec"

.default_template: &default_definition
  image: jangrewe/gitlab-ci-android

  variables:
    CACHE_DIR: "/builds/mobile/retrograph/cache"
    GRADLE_USER_HOME: "${CACHE_DIR}/gradle"
    GRADLE_OPTS: "-Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.caching=true"

  before_script:
    - echo $CACHE_DIR
    - echo $GRADLE_USER_HOME
    - echo $GRADLE_OPTS
    - mkdir -p $GRADLE_USER_HOME
    - rm -rf gradle.properties
    - echo -e "org.gradle.parallel=true" >> gradle.properties
    - echo -e "org.gradle.daemon=false" >> gradle.properties
    - echo -e "org.gradle.caching=true" >> gradle.properties
    - echo -e "org.gradle.jvmargs=-Xms256m -Xmx4096m" >> gradle.properties
    - cat gradle.properties
    - rm -rf gradle.properties
    - chmod +x ./gradlew
    - du -sh $CACHE_DIR || true
    - du -sh $CACHE_DIR/* || true
    - du -sh $GRADLE_USER_HOME/* || true
    - ./gradlew --stop

  after_script:
    - du -sh $CACHE_DIR || true
    - du -sh $CACHE_DIR/* || true
    - du -sh $GRADLE_USER_HOME/* || true

  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - $CHACHE_DIR

# SONARQUBE TEMPLATE

.sonarqube_template: &sonarqube_definition
  image: openjdk:8-jre-alpine

  variables:
    SONAR_SCANNER_VERSION: "3.0.3.778"
    SONAR_SCANNER_ARGS: >
      -Dsonar.host.url=$SONARQUBE_URL
      -Dsonar.login=$SONARQUBE_TOKEN
      -Dsonar.projectKey=$CI_PROJECT_NAMESPACE:$CI_PROJECT_NAME
      -Dsonar.projectVersion=$CI_JOB_ID
      -Dsonar.sources=$SOURCES_PATH
      -Dsonar.tests=$TESTS_PATH
      -Dsonar.java.binaries=$BINARIES_PATH
      -Dsonar.java.coveragePlugin=jacoco
      -Dsonar.jacoco.reportPaths=$JACOCO_EXEC_FILE

  before_script:
    - apk add --no-cache ca-certificates wget git
    - update-ca-certificates
    - wget https://s3-eu-west-1.amazonaws.com/kiwi-ci/sonar-scanner-cli-$SONAR_SCANNER_VERSION.zip
    - unzip sonar-scanner-cli-$SONAR_SCANNER_VERSION.zip

  allow_failure: true

# TASKS

assemble:
  stage: build

  <<: *default_definition

  script:
    - ./gradlew assemble

  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
      - $BINARIES_PATH
    expire_in: 1 week

test:
  stage: test

  <<: *default_definition

  script:
    - ./gradlew test jacocoTestReport

  dependencies: [assemble]

  artifacts:
    paths:
      - $BINARIES_PATH
      - $JACOCO_EXEC_FILE
    expire_in: 1 week

sonar-scanner:
  stage: quality

  <<: *sonarqube_definition

  only:
    - master

  script:
    - sonar-scanner-$SONAR_SCANNER_VERSION/bin/sonar-scanner $SONAR_SCANNER_ARGS

  dependencies: [test]

sonar-scanner-branch:
  stage: quality

  <<: *sonarqube_definition

  except:
    - master

  script:
    - sonar-scanner-$SONAR_SCANNER_VERSION/bin/sonar-scanner $SONAR_SCANNER_ARGS -Dsonar.branch.name=$CI_COMMIT_REF_NAME

  dependencies: [test]

uploadArchives:
  stage: deploy

  <<: *default_definition

  script:
    - ./gradlew uploadArchives

  dependencies: [assemble, test]

  when: manual
